app_cart_pick_up:
    path: /api/cart/pick-up
    methods: [POST]
    defaults:
        _controller: app.controller.cart:pickUpAction
        _format: json

app_cart_add_product:
    path: /api/cart/add-product
    methods: [POST]
    defaults:
        _controller: app.controller.cart:addProductAction
        _format: json

app_cart_change_product_quantity:
    path: /api/cart/change-product-quantity
    methods: [POST]
    defaults:
        _controller: app.controller.cart:changeProductQuantityAction
        _format: json

app_cart_remove_product_from_cart:
    path: /api/cart/remove-product
    methods: [POST]
    defaults:
        _controller: app.controller.cart:removeProductAction
        _format: json

app_cart_clear:
    path: /api/cart/clear
    methods: [POST]
    defaults:
        _controller: app.controller.cart:clearAction
        _format: json
